### ISSUE TITLE
Emacs redraws on some actions

### ISSUE THREAD

**Issue by dzervas** [robert-zaremba/auto-virtualenvwrapper.el#7]
I just did `(require auto-virtualenvwrapper)` and emacs now redraws on some actions (e.g. on save) and it's not pleasant to the eyes. Do you have any idea to mitigate this?

Also note that this happens to all major modes, not only in python-mode

**Comment by robert-zaremba** [comment]
Which Emacs version do you use?

**Comment by dzervas** [comment]
26.1

**Comment by dzervas** [comment]
Not using this anymore, so closing

**Comment by robert-zaremba** [comment]
OK, sorry I couldn't replicate your issue.
